### ISSUE TITLE
can't restart my docker

### ISSUE THREAD

**Issue by xgodon** [m-creations/docker-fusiondirectory#1]
when i create a container like that :
docker run --name fd -d -it \
-p 12080:80 \
-e LDAP_DOMAIN=example.com \
-e LDAP_ROOTPW=secret \
-e LDAP_ROOTDN="cn=admin,dc=example,dc=com" \
--link ldap:ldap-server  \
mcreations/fusiondirectory

i can see it works
then i do 
docker stop fd
docker start fd
docker ps -a
my docker is like  "Exited (0) 11 seconds ago"

i don't understand :x can you help me?

**Comment by darabi** [comment]
Hi Xavier (I hope that's your correct name),

thanks for trying out the container and sorry that it doesn't work out of the box.

I'll check this and get back to you.

Cheers

Kambiz

**Comment by xgodon** [comment]
Thanks a lot for your concern!
(and yeah you guessed right for my name)

**Comment by darabi** [comment]
When testing with `docker start -ai fd` with Docker version 1.9.1, I can restart the container reliably.

Is this the case for you too? What is your Docker version?

**Comment by xgodon** [comment]
Docker version 1.9.1, build a34a1d5
no its not working. Maybe i corrupted my docker installation (i'm not used to docker)
i'll try on clean install and come back to you!

**Comment by darabi** [comment]
I don't think that you should re-install Docker.

I'm sure this is a problem of the image somehow, because I also could
reproduce it once or twice, but not always.

And I observed that starting it in the 'foreground' with -ai reliably
started the container.

I will try to investigate further.

**Comment by darabi** [comment]
Hi Xavier,

my apologies for not getting back to you. This issue completely disappeared from my radar.

I tried to reproduce the bug with the current version of Docker

```
$ docker --version
Docker version 1.12.1, build 23cf638
```

Stopping and starting the container works as expected, so I guess it was something related to Docker itself. Can you please try again with a current version and report back?

Thank you

**Comment by boykov** [comment]
There is a problem with apache2.pid, you can see "httpd (pid 22) already running" message in the log. [Solution:](https://github.com/docker-library/php/issues/187) you have to rebuild Docker image with [rm -f /var/run/apache2/apache2.pid](https://github.com/docker-library/php/blob/bdfd0fc1d19102cd6f951614072a51eabf7191bf/5.6/apache/apache2-foreground) in [start-fd](https://github.com/m-creations/docker-fusiondirectory/blob/master/image/root/start-fd)

**Comment by darabi** [comment]
Thank you, @boykov. That's it!

I don't know why I could restart the stopped container or maybe I made another mistake while testing.

Will push a new version.
