### ISSUE TITLE
Issue with LDAP server binding

### ISSUE THREAD

**Issue by slauriere** [m-creations/docker-fusiondirectory#2]
Hello Kambiz, 

While giving a try to the image, both images 'fusiondirectory-ldap' and 'fusiondirectory' are properly launched that's great, however I stumbled on an error when trying to connect to the FusionDirectory user interface at http://localhost:12080/. Here's below what I get on that page. Does the latest version behave differently on your end? Would you know what could cause this error?

`FATAL: Error when connecting the LDAP. Server said 'Could not bind to cn=Manager,dc=example,dc=com (while operating on LDAP server ldap://ldap-server:389)'
`

**Comment by darabi** [comment]
Hi Stéphane,

sorry for the late reply: I'm travelling and have limited access to internet.

@rezarahimi  will look into this issue and get back to you.

Thanks for reporting the problem.

**Comment by rezarahimi** [comment]
Hello Stéphane,

Please provide all exact **docker run** commands as test case which we can reproduce the error and find what is the problem.

**Comment by rezarahimi** [comment]
Hello Stéphane,

I found the problem.

Please try following command to run ldap:

```
docker run -d -p 12080:80 -e LDAP_DOMAIN=example.com -e LDAP_ROOTPW=secret -e LDAP_ROOTDN="cn=admin,dc=example,dc=com" --link ldap:ldap-server mcreations/fusiondirectory
```

I have changed cn=Manager to cn=admin in LDAP_ROOTDN parameter.

**Comment by rezarahimi** [comment]
I fixed and pushed the README.md .

**Comment by slauriere** [comment]
Hi Kambiz and Reza, It works indeed! Great. Thanks a lot! I noticed in the meantime via the FusionDirectory team that the image is used at [docker:mikefaille/docker-debian-fusiondirectory/](https://hub.docker.com/r/mikefaille/docker-debian-fusiondirectory/) as well - with a wrong CN, I'll see how Mike can get notified.

**Comment by mikefaille** [comment]
Thank you for this notice @slauriere.
