### ISSUE TITLE
cant login as admin

### ISSUE THREAD

**Issue by mdy405** [m-creations/docker-fusiondirectory#6]
I created a contained for Fusion directory for my ldap server using this Command : 
docker run -d -p 12080:80 -e LDAP_DOMAIN=example.com -e LDAP_ROOTPW=secret -e LDAP_ROOTDN="cn=admin,dc=example,dc=com" --link ldap:ldap-server mcreations/fusiondirectory

but i cant login  as fd-admin using the LDAP_ROOTPW I specified

any help!...thx

**Comment by mdy405** [comment]
when I run fusiondirectory-setup --check-ldap i got : 

! There is no admin ACL roleNo valid admin account found, do you want to create it ? [Yes/No]?
i try to create one the result is the following error: 

! failed to add LDAP's uid=fd-admin,ou=people,dc=openldap,dc=company,dc=com entry - LDAP_INVALID_SYNTAX: Some part of the request contained an invalid syntax. It could be a search
with an invalid filter or a request to modify the schema and the given
schema has a bad syntax.

**Comment by darabi** [comment]
Thanks for reporting this. We will look into this and get back to you.

**Comment by rezarahimi** [comment]
Just I have tested the two docker run commands in the [README.md](https://github.com/m-creations/docker-fusiondirectory) and it works as follows:
```
docker run -d --name ldap -e LDAP_DOMAIN=example.com -e LDAP_ROOTPW=secret mcreations/fusiondirectory-ldap
```
```
docker run -d -p 12080:80 -e LDAP_DOMAIN=example.com -e LDAP_ROOTPW=secret -e LDAP_ROOTDN="cn=admin,dc=example,dc=com" --link ldap:ldap-server mcreations/fusiondirectory
```
Status of dockers:
```
 docker ps
CONTAINER ID        IMAGE                             COMMAND             CREATED             STATUS              PORTS                   NAMES
4c68b4adbde1        mcreations/fusiondirectory        "/start-fd"         8 minutes ago       Up 8 minutes        0.0.0.0:12080->80/tcp   suspicious_archimedes
91ad79783dae        mcreations/fusiondirectory-ldap   "/start-slapd-fd"   12 minutes ago      Up 12 minutes       389/tcp                 ldap
```
And I could login with fd-admin/secret as follows
![image](https://user-images.githubusercontent.com/828911/42437250-d3f46738-835c-11e8-9a87-7bfb9b63f90b.png)

**You could not run the mcreations/fusiondirectory docker against any existing running ldap server. You need a running ldap server based on the mcreations/fusiondirectory-ldap docker.**
